import { ArrowLeft, Download, TrendingUp, DollarSign, Target, Lightbulb } from 'lucide-react';
import { Consultation } from '../lib/supabase';

type PricingAnalysisResultProps = {
  consultation: Consultation;
  onBack: () => void;
};

export function PricingAnalysisResult({ consultation, onBack }: PricingAnalysisResultProps) {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const handleDownload = () => {
    // Create a text file with the analysis
    const content = `
PRICEWISE - PRICING ANALYSIS REPORT
Generated: ${formatDate(consultation.created_at)}

BUSINESS INFORMATION
====================
Type: ${consultation.business_type}
Market: ${consultation.target_market}

OFFERING DESCRIPTION
====================
${consultation.product_description}

COST STRUCTURE
==============
${consultation.cost_to_deliver}

COMPETITIVE ANALYSIS
====================
${consultation.competitor_pricing}

VALUE PROPOSITION
=================
${consultation.value_proposition}

PRICING RECOMMENDATION
======================
${consultation.pricing_recommendation}

---
Generated by HowMuchShouldIPrice - AI-Powered Price Provider
https://howmuchshouldiprice.com
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pricing-analysis-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-slate-600 hover:text-slate-800 transition"
        >
          <ArrowLeft className="w-5 h-5" />
          Back to Dashboard
        </button>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-4 py-2 bg-olive-600 text-white rounded-lg hover:bg-olive-700 transition font-medium"
        >
          <Download className="w-5 h-5" />
          Download Report
        </button>
      </div>

      <div className="bg-white rounded-2xl shadow-lg overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-olive-600 to-olive-700 p-8 text-white">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-white bg-opacity-20 p-3 rounded-xl">
              <TrendingUp className="w-8 h-8" />
            </div>
            <div>
              <h2 className="text-3xl font-bold">Your AI-Powered Pricing Analysis</h2>
              <div className="text-beige-100 mt-2 text-sm">
                Generated: {formatDate(consultation.created_at)}
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2 bg-white bg-opacity-10 rounded-lg px-4 py-2 inline-block">
            <Lightbulb className="w-5 h-5" />
            <span className="text-sm">Powered by DeepSeek V3 AI</span>
          </div>
        </div>

        {/* AI Analysis */}
        <div className="p-8">
          <div className="bg-gradient-to-br from-beige-50 to-beige-100 border-2 border-beige-200 rounded-xl p-8 mb-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="bg-olive-100 p-3 rounded-lg">
                <DollarSign className="w-6 h-6 text-olive-600" />
              </div>
              <h3 className="text-2xl font-bold text-olive-900">Pricing Recommendation</h3>
            </div>
            <div className="prose prose-slate max-w-none text-slate-700 whitespace-pre-wrap leading-relaxed">
              {consultation.pricing_recommendation}
            </div>
          </div>

          {/* Input Summary */}
          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-6">
              <div className="bg-beige-50 rounded-xl p-6 border border-beige-200">
                <div className="flex items-center gap-2 mb-3">
                  <Target className="w-5 h-5 text-olive-600" />
                  <h4 className="font-semibold text-slate-800">Business Type</h4>
                </div>
                <p className="text-slate-600">{consultation.business_type}</p>
              </div>

              <div className="bg-beige-50 rounded-xl p-6 border border-beige-200">
                <div className="flex items-center gap-2 mb-3">
                  <Target className="w-5 h-5 text-olive-600" />
                  <h4 className="font-semibold text-slate-800">Target Market</h4>
                </div>
                <p className="text-slate-600">{consultation.target_market}</p>
              </div>

              <div className="bg-beige-50 rounded-xl p-6 border border-beige-200">
                <div className="flex items-center gap-2 mb-3">
                  <DollarSign className="w-5 h-5 text-olive-600" />
                  <h4 className="font-semibold text-slate-800">Cost Structure</h4>
                </div>
                <p className="text-slate-600">{consultation.cost_to_deliver}</p>
              </div>
            </div>

            <div className="space-y-6">
              <div className="bg-beige-50 rounded-xl p-6 border border-beige-200">
                <div className="flex items-center gap-2 mb-3">
                  <TrendingUp className="w-5 h-5 text-olive-600" />
                  <h4 className="font-semibold text-slate-800">Offering Description</h4>
                </div>
                <p className="text-slate-600">{consultation.product_description}</p>
              </div>

              <div className="bg-beige-50 rounded-xl p-6 border border-beige-200">
                <div className="flex items-center gap-2 mb-3">
                  <TrendingUp className="w-5 h-5 text-olive-600" />
                  <h4 className="font-semibold text-slate-800">Competition</h4>
                </div>
                <p className="text-slate-600">{consultation.competitor_pricing}</p>
              </div>

              <div className="bg-beige-50 rounded-xl p-6 border border-beige-200">
                <div className="flex items-center gap-2 mb-3">
                  <Lightbulb className="w-5 h-5 text-olive-600" />
                  <h4 className="font-semibold text-slate-800">Your Unique Value</h4>
                </div>
                <p className="text-slate-600">{consultation.value_proposition}</p>
              </div>
            </div>
          </div>

          {/* Action CTA */}
          <div className="mt-8 bg-gradient-to-r from-olive-600 to-olive-700 rounded-xl p-6 text-white text-center">
            <h3 className="text-xl font-bold mb-2">Ready to implement your pricing?</h3>
            <p className="text-beige-100 mb-4">
              Use this analysis to confidently price your offering and maximize your revenue.
            </p>
            <button
              onClick={handleDownload}
              className="px-6 py-3 bg-white text-olive-600 rounded-lg hover:bg-beige-50 transition font-semibold"
            >
              Download Full Report
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

